version: 2

jobs:
  build:
    docker:
      - image: circleci/python:3.7
    steps:
      - checkout
      - run:
          name: Install
          command: |
            sudo apt-get install texlive-base
            sudo apt-get install texlive
            sudo apt-get install texlive-latex-extra
            sudo apt-get install texlive-latex-recommended
            sudo apt-get install texlive-fonts-recommended
            sudo apt-get install texlive-latex-extra
            sudo apt-get install texlive-science
            sudo apt-get install lmodern
            sudo apt-get install texlive-lang-french
            sudo pip3 install numpy
            sudo pip3 install scipy
            sudo pip3 install matplotlib
            sudo pip3 install jupyter
            sudo pip3 install openturns
            sudo pip3 install black
            sudo pip3 install flake8
      - run:
          name: Install Python deps in a venv with pip
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt
            rm -r venv
      - run:
          name: Install package in a venv with setup
          command: |
            python3 -m venv venv
            source venv/bin/activate
            pip install -r requirements.txt
            python setup.py install
            mkdir tmp
            cp demo.py tmp
            cd tmp
            python demo.py
            cd ..
            rm -r tmp
            rm -r venv
      - run:
          name: Create package source distribution
          command: |
            python3 -m venv venv
            source venv/bin/activate
            python setup.py sdist
            rm -r venv
      - run:
          name: Check style of Python Scripts with black
          command: |
            black --check retraites
      - run:
          name: Check style of Python Scripts with flake8
          command: |
            flake8 retraites
      - run:
          name: Check style of Notebooks with black-nb
          command: |
            black-nb --check .
      - run:
          name: Build and test - global
          command: ./.circleci/run_docker_linux.sh

